CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(512) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  owner_id BIGINT,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  available BOOLEAN NOT NULL,
  CONSTRAINT pk_item PRIMARY KEY (id),
  CONSTRAINT fk_owner FOREIGN KEY (owner_id) references users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  item_id BIGINT,
  booker_id BIGINT,
  status VARCHAR(255) NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  CONSTRAINT pk_booking PRIMARY KEY (id),
  CONSTRAINT fk_booker FOREIGN KEY (booker_id) references users (id) ON DELETE CASCADE,
  CONSTRAINT fk_item FOREIGN KEY (item_id) references items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  text VARCHAR(255) NOT NULL,
  item_id BIGINT,
  author_id BIGINT,
  created TIMESTAMP NOT NULL,
  CONSTRAINT pk_comment PRIMARY KEY (id),
  CONSTRAINT fk_author FOREIGN KEY (author_id) references users (id) ON DELETE CASCADE,
  CONSTRAINT fk_item_id FOREIGN KEY (item_id) references items (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  description VARCHAR(255) NOT NULL,
  requester_id BIGINT NOT NULL,
  created TIMESTAMP NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (id),
  CONSTRAINT fk_requester FOREIGN KEY (requester_id) references users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS item_requests_answers (
    item_id BIGINT NOT NULL,
    request_id BIGINT NOT NULL,
    CONSTRAINT fk_request_id FOREIGN KEY (request_id) references item_requests (id) ON DELETE CASCADE,
    CONSTRAINT fk_answered_item_id FOREIGN KEY (item_id) references items (id) ON DELETE CASCADE
);